### ISSUE TITLE
Nelze udělat clean install -  Python 3.5 není podporovaný, ale je vyžadovaný

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/dashboard#17]
Ahoj Honzo, zkusil jsem si nainstalovat dashboard lokálně kvůli zjištování statistik z předchozích ročníků.

Spálil jsem se na mnoha místech, například na tom že deklaruješ že je třeba Python 3.5, ale Pandas od verze 1.0.0 už podporuje jenom 3.6+.

Stejně tak nejdou dostupné další balíčky. Taky není dostupný například libmysqlclient-dev, který je třeba doinstalovat.
Also, na pořadí balíčků záleží, pokud nemáš nainstalovaný jupyter hned na začátku tak se hide-code zasekne. Atd, atd.

Následující postup je funkční pro čisté Ubuntu 18.04 LTS

```sh
# Fresh ubuntu 18.04 LTS

sudo apt update
sudo apt install -y python3 python3-dev python3-venv libmysqlclient-dev virtualenv gcc make

git clone https://github.com/fi-ksi/dashboard.git
cd dashboard/

virtualenv -p python3 ksi-py3-venv
source ksi-py3-venv/bin/activate

pip3 install jupyter

cat requirements.txt | grep -v "pkg-resources==" > requirements_new.txt
mv requirements_new.txt requirements.txt


pip3 install -r requirements.txt
```

**Comment by BorysekOndrej** [comment]
Also, for WSL
```jupyter notebook --no-browser```

**Comment by BorysekOndrej** [comment]
Also, dle instrukcí výše to jde spustit jako notebook, ale ne exportovat do html přes make.

```
(ksi-py3-venv) redactedUsername@redactedHostname:/redactedPath/dashboard$ make all
ksi-py3-venv/bin/python3 export_monitoring_notebook notebooks/feedback-text.ipynb build/feedback-text.html
Traceback (most recent call last):
  File "export_monitoring_notebook", line 52, in <module>
    export_notebook_to_html(notebook, output_path)
  File "export_monitoring_notebook", line 37, in export_notebook_to_html
    html, _resources = html_exporter.from_notebook_node(notebook)
  File "/redactedPath/dashboard/ksi-py3-venv/lib/python3.6/site-packages/nbconvert/exporters/html.py", line 95, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/redactedPath/dashboard/ksi-py3-venv/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 322, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/redactedPath/dashboard/ksi-py3-venv/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 114, in template
    self._template_cached = self._load_template()
  File "/redactedPath/dashboard/ksi-py3-venv/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 293, in _load_template
    return self.environment.get_template(template_file)
  File "/redactedPath/dashboard/ksi-py3-venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/redactedPath/dashboard/ksi-py3-venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/redactedPath/dashboard/ksi-py3-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 497, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: ksi-py3-venv/lib/python3.7/site-packages/jupyter_contrib_nbextensions/templates/nbextensions.tpl
Makefile:6: recipe for target 'build/feedback-text.html' failed
make: *** [build/feedback-text.html] Error 1
```

**Comment by BorysekOndrej** [comment]
Notebook je pokrytý commitem https://github.com/fi-ksi/dashboard/commit/166ff8c0b8f6e7a53a373d8558baa92822662a94 do branche ondra, časem udělám PR.
Build už řešit nebudu, teď ho nepotřebuji.
